### ISSUE TITLE
Bribe Support

### ISSUE THREAD

**Issue by electron0zero** [razorpay/jquery#1]
It will be like [lazy loading](https://en.wikipedia.org/wiki/Lazy_loading) but it will be known as bribe
see also
http://jquery.eisbehr.de/lazy/

**Comment by riteshzefo** [comment]
+1

**Comment by gaa94** [comment]
+1

**Comment by sreetamdas** [comment]
+1

**Comment by vkscool** [comment]
+1

**Comment by captn3m0** [comment]
>Bribe is a fast, feature-rich, extensible and lightweight delayed content loading plugin for rQuery.
