### ISSUE TITLE
This is actually not a real thing

### ISSUE THREAD

**Issue by mayukhnair** [razorpay/jquery#2]
### Description ###

Yaar April fool se badhkar yeh legit hota toh sahi hota. :P

**Comment by captn3m0** [comment]
I suspect you missed out the UTF-8 charset. It works completely fine if you add that. Here is a demo for `.bhangra()`:

https://rawgit.com/captn3m0/6c9775725715bb91af5d106ba7a7c616/raw/1f6382e8a92576aa4bae0ca6e20f24a98d2f62a7/index.html
